### ISSUE TITLE
Increment counter

### ISSUE THREAD

**Issue by Robotto** [MrSquidson/school-stuff#1]
https://github.com/MrSquidson/school-stuff/blob/af7230b509df469bc0931cb89025e18da6535d22/Silly%20Dictionary%20Stuff/Football%20trip/fodboldtur.py#L153

Antallet bør sættes til 3 😏

**Comment by MrSquidson** [comment]
Done!- Jeg undskylder men one-lineren kaldte på mig

**Comment by Robotto** [comment]
De gør de tit... Det er lissom parkour: mega lækker måde at komme ned af en trappe, men umuligt at samarbejde om, uden at nogen brækker nakken. ¯\_(ツ)_/¯
